USE recipe_app;
 
INSERT INTO users (user_id, name, email, password_hash) VALUES
(1, 'Jan Hoang',      'jan@example.com',     '$2y$10$gPcF.exmih/ANdKCaEYQsOlTw4MGsMee93pscgz02DQyfJkqz6Kc6'),
(2, 'Gabriel Andino', 'gabriel@example.com', '$2y$10$c6HT4KFglRB73r3HjeXIXOiesb2.lwtXciUztoFfVC8S.9yRis.6a');
 
INSERT INTO categories (category_id, name) VALUES
(1,'Starter'), (2,'Main'), (3,'Dessert'), (4,'Side'), (5,'Breakfast'),
(6,'Vegetarian'), (7,'Vegan'), (8,'Beef'), (9,'Lamb'), (10,'Quick');
 
INSERT INTO recipes
  (recipe_id, title, description, total_mins, servings, difficulty, cuisine) VALUES
(1,'Spaghetti Bolognese',
 'A slow-simmered beef and tomato sauce served over spaghetti. Freezes well.',
 105, 4, 'medium', 'Italian'),
(2,'Vegan Pancakes',
 'Fluffy pancakes with no eggs or dairy. One bowl, ten minutes.',
 25, 4, 'easy', 'American'),
(3,'Healthy Pizza',
 'Thin-crust pizza loaded with roasted vegetables and a light scatter of mozzarella.',
 40, 2, 'medium', 'Italian'),
(4,'Easy Lamb Biryani',
 'Spiced lamb layered with basmati rice and baked until the rice steams through.',
 80, 6, 'hard', 'Indian'),
(5,'Couscous Salad',
 'Lemon-dressed couscous with chickpeas, cucumber and plenty of herbs.',
 20, 4, 'easy', 'Moroccan');
 
INSERT INTO recipe_categories (recipe_id, category_id) VALUES
(1,2),(1,8),
(2,5),(2,6),(2,7),(2,10),
(3,2),(3,6),
(4,2),(4,9),
(5,1),(5,4),(5,6),(5,7),(5,10);
 
INSERT INTO ingredients (recipe_id, name, quantity) VALUES
(1,'olive oil','2 tbsp'),
(1,'onion','1, finely chopped'),
(1,'carrot','1, diced'),
(1,'celery','2 sticks, diced'),
(1,'garlic','3 cloves, crushed'),
(1,'beef mince','500g'),
(1,'red wine','150ml'),
(1,'chopped tomatoes','2 x 400g tins'),
(1,'tomato puree','2 tbsp'),
(1,'dried oregano','1 tsp'),
(1,'spaghetti','400g'),
(1,'parmesan','40g, grated'),
(2,'plain flour','200g'),
(2,'baking powder','2 tsp'),
(2,'caster sugar','2 tbsp'),
(2,'salt','pinch'),
(2,'soya milk','300ml'),
(2,'sunflower oil','2 tbsp'),
(2,'maple syrup','to serve'),
(3,'strong white bread flour','250g'),
(3,'fast-action dried yeast','7g sachet'),
(3,'olive oil','1 tbsp'),
(3,'passata','150ml'),
(3,'garlic','1 clove, crushed'),
(3,'red pepper','1, sliced'),
(3,'courgette','1, sliced'),
(3,'cherry tomatoes','8, halved'),
(3,'mozzarella','80g, torn'),
(3,'basil','to serve'),
(4,'lamb shoulder','700g, diced'),
(4,'natural yoghurt','200g'),
(4,'garam masala','2 tsp'),
(4,'ground turmeric','1 tsp'),
(4,'ground cumin','2 tsp'),
(4,'root ginger','20g, grated'),
(4,'garlic','4 cloves, crushed'),
(4,'green chilli','2, sliced'),
(4,'onion','2, thinly sliced'),
(4,'basmati rice','400g'),
(4,'butter','30g'),
(4,'coriander','to serve'),
(5,'couscous','200g'),
(5,'vegetable stock','300ml, hot'),
(5,'chickpeas','400g tin, drained'),
(5,'cucumber','half, diced'),
(5,'cherry tomatoes','200g, halved'),
(5,'red onion','half, finely sliced'),
(5,'flat-leaf parsley','20g, chopped'),
(5,'mint','10g, chopped'),
(5,'lemon','1, juice and zest'),
(5,'olive oil','3 tbsp');
 
INSERT INTO steps (recipe_id, step_no, instruction, duration_mins) VALUES
(1,1,'Heat the oil in a large pan. Cook the onion, carrot and celery with a pinch of salt until soft but not browned.',10),
(1,2,'Stir in the garlic and cook for one minute.',1),
(1,3,'Turn the heat up, add the mince and fry until no pink remains.',8),
(1,4,'Pour in the wine and let it bubble until reduced by half.',5),
(1,5,'Add the tomatoes, tomato puree and oregano. Simmer gently, part-covered, stirring now and then.',60),
(1,6,'Cook the spaghetti in salted boiling water until al dente, then drain.',10),
(1,7,'Season the sauce, toss the spaghetti through it and serve with grated parmesan.',3),
(2,1,'Whisk the flour, baking powder, sugar and salt together in a bowl.',2),
(2,2,'Pour in the soya milk and oil. Whisk just until combined - small lumps are fine.',3),
(2,3,'Rest the batter while the pan heats. This gives a better rise.',5),
(2,4,'Heat a lightly oiled non-stick pan over a medium heat and add the batter in ladlefuls.',2),
(2,5,'Cook until bubbles cover the surface, then flip and cook until golden. Repeat with the rest.',12),
(2,6,'Serve warm with maple syrup.',1),
(3,1,'Mix the flour, yeast and salt. Add the oil and 150ml warm water, then bring together into a soft dough.',5),
(3,2,'Knead on a floured surface until smooth and elastic.',8),
(3,3,'Cover and leave somewhere warm until roughly doubled in size.',20),
(3,4,'Heat the oven to its highest setting with a baking tray inside. Stir the garlic into the passata.',5),
(3,5,'Stretch the dough out thinly, spread with sauce, then scatter over the vegetables and mozzarella.',7),
(3,6,'Slide onto the hot tray and bake until the crust is blistered and the base is crisp. Finish with basil.',12),
(4,1,'Mix the lamb with the yoghurt, spices, ginger, garlic, chilli and salt. Leave to marinate.',15),
(4,2,'Fry the onions in oil until deep golden. Lift half out and keep for the topping.',15),
(4,3,'Add the lamb and cook until the yoghurt reduces to a thick paste. Add a splash of water, cover and simmer until tender.',35),
(4,4,'Boil the rinsed rice in salted water for five minutes only, then drain well. It should still have bite.',8),
(4,5,'Spread the rice over the lamb, dot with butter, scatter the reserved onions and cover tightly.',5),
(4,6,'Cook on the lowest heat, undisturbed, until the rice is steamed through. Rest, then fork through and serve.',20),
(5,1,'Put the couscous in a bowl, pour over the hot stock, cover with a plate and leave to absorb.',8),
(5,2,'Fork through to separate the grains and let it cool.',5),
(5,3,'Whisk the lemon juice and zest with the olive oil and black pepper.',2),
(5,4,'Add the chickpeas, cucumber, tomatoes and red onion to the couscous.',4),
(5,5,'Pour over the dressing, add the herbs and toss. Check the seasoning before serving.',3);
 
INSERT INTO ratings (user_id, recipe_id, rating, comment) VALUES
(1,1,4,'Really good flavour and the sauce came out rich. I would probably use slightly less wine next time.'),
(2,1,5,'Easy to follow and turned out better than expected. Definitely making this again.'),
(1,2,5,'Very simple recipe and the pancakes came out light and fluffy.'),
(2,2,4,'Good quick breakfast. I served mine with fruit instead of maple syrup.'),
(1,3,4,'The crust worked well but I added some extra seasoning to the vegetables.'),
(2,3,5,'Really enjoyed this. The thin base was crisp and the toppings worked well together.'),
(1,4,5,'Takes a bit of preparation but the finished biryani was worth the effort.'),
(2,4,4,'Great flavour overall. I would use a little less chilli next time.'),
(1,5,4,'Fresh and easy to prepare. Works well as a lunch or side dish.'),
(2,5,3,'Nice recipe but I found it slightly dry, so I added some extra lemon dressing.');
 
INSERT INTO favourites (user_id, recipe_id) VALUES
(1,1),(1,3),(1,5),
(2,2),(2,4),(2,5);